server:
  port: 8787

spring:
  application:
    name: fixEngine

#Quickfixj
quickfixj:
  currency: AFA,DZD,ADP,ARS,AMD,AWG,AUD,AZM,BSD,BHD,THB,PAB,BBD,BYN,BEF,BZD,BMD,VEB,BOB,BRL,BND,BIF,XOF,XAF,XPF,CAD,CVE,KYD,GHC,CLP,COP,KMF,BAM,NIO,CRC,CUP,CYP,CZK,GMD,DKK,MKD,DEM,DJF,STD,DOP,VND,GRD,XCD,EGP,SVC,ETB,EUR,FKP,FJD,HUF,CDF,FRF,GIP,HTG,PYG,GNF,GWP,GYD,HKD,UAH,ISK,INR,IRR,IQD,IEP,ITL,JMD,JOD,KES,PGK,LAK,EEK,HRK,KWD,MWK,ZMK,AOR,MMK,GEL,LVL,LBP,ALL,HNL,SLL,ROL,BGL,LRD,LYD,SZL,LTL,LSL,LUF,MGF,MYR,MTL,TMM,FIM,MUR,MZM,MXN,MXV,MDL
  jmx-enabled: true
  startup-timeout: 20s
  config: "classpath:quickfixj.cfg"
  dictionary: "classpath:FIX50SP1.xml"

#监控全部的元数据信息
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    quickfixj.enabled: true
  metrics.export:
    #Simple In memory (maybe later integrate with graphite or prometheus?)
    simple.enabled: true
