server:
  port: 8787

spring:
  application:
    name: fixEngine

#Quickfixj
quickfixj:
  jmx-enabled: true
  startup-timeout: 20s
  config: "classpath:quickfixj.cfg"
  dictionary: "classpath:FIX50SP1.xml"

#监控全部的元数据信息
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    quickfixj.enabled: true
  metrics.export:
    #Simple In memory (maybe later integrate with graphite or prometheus?)
    simple.enabled: true
